### ISSUE TITLE
[COL] After updating from Maven

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/MMDBuckets#5]
https://pastebin.com/CS0xR8Hq

MC 1.12.2
Forge 2619
AdditionalLootTables-1.12-2.0.3.37
OreSpawn-1.12-3.2.2.114
BaseMetals-1.12-2.5.0-beta4.155.jar
ModernMetals-1.12-2.5.0-beta4.95.jar
BaseMinerals-1.12-2.5.0-beta4.27.jar
NetherMetals-1.12-1.2.0-beta2.35.jar
EndMetals-1.12-1.2.0-beta2.24.jar
Buckets-1.12-0.0.1-alpha2.11.jar

**Comment by dshadowwolf** [comment]
The creative tabs code was changed in the latest -beta4 release -- MMD Buckets will get an update soonish

**Comment by knoxhack** [comment]
...

**Comment by knoxhack** [comment]
just a reminder ^^  trying to get it on the dev server

**Comment by dshadowwolf** [comment]
@knoxhack just needs a CF push from Jenkins - I'll get that today or tomorrow when I push 1.7c to the staff testing server

**Comment by dshadowwolf** [comment]
fixed in -dev - closing
