### ISSUE TITLE
Crash with Buckets-1.12-0.0.1-beta1.15.jar

### ISSUE THREAD

**Issue by YaibaToKen** [MinecraftModDevelopmentMods/MMDBuckets#7]
Using the latest stable versions of BaseMetals, ModernMetals, NetherMetals, EndMetals, OreSpawn at this point and Forge 2768.
https://gist.github.com/YaibaToKen/c8e20eaa8c17d165003fa1530dca8480

**Comment by dshadowwolf** [comment]
There is a massive change in the API provided by BaseMetals that Buckets has not, yet, been updated to work with. That's on the list, but we're still a very small team, sadly...

**Comment by BraniyaKz** [comment]
I, too, have met this formidable crash...

_- BranTuna_

**Comment by dshadowwolf** [comment]
Let me repeat myself: There was an incompatible change in one of the internal API's of BaseMetals. THis has broken the build of Buckets that is available. We have manpower issues, so this has not, yet, been addressed.

**Comment by YaibaToKen** [comment]
@dshadowwolf is this still a problem?

**Comment by dshadowwolf** [comment]
Will be fixing soon to the version of *Metals currently under test - this
next version of *Metals changes some dependency requirements and introduces
the "long under development" MMDLib as a separate mod (finally), replacing
the version that was prematurely released prior to me joining the team.


DRH

**Comment by dshadowwolf** [comment]
Fixed in -dev - will leave this open until the release
