### ISSUE TITLE
No Textures

### ISSUE THREAD

**Issue by Darkhax** [MinecraftModDevelopmentMods/MMDBuckets#8]
Most of the buckets in the mod seem to have missing textures. This is with 0.0.1 beta 1. 

![image](https://user-images.githubusercontent.com/2250798/49562811-fb904b80-f914-11e8-8943-3fc5a793b451.png)
![image](https://user-images.githubusercontent.com/2250798/49562816-ff23d280-f914-11e8-83e2-827389b390ca.png)

**Comment by dshadowwolf** [comment]
There was no "-beta1" at the time - there was, however, an -alpha2...

But... Unable to reproduce, marking this fixed.
